version: '3'
services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/mount:/var/lib/postgresql/data
      - ./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

  redis:
    restart: always
    image: "redis:latest"
    container_name: incubator-redis
    ports:
      - "6379:6379"
  redisinsight:
    image: redislabs/redisinsight:latest
    ports:
      - "8001:8001"

